### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/sparkn2#64]
- [x] complete auth (save token, redirection to private resources, check for existence of token)
- [ ] refactor profile page reducers and actions plus styling
- [ ] add fake avatar for the user
- [ ] refactor reducers and actions for Feed screen
- [ ] refactor reducers and actions for Calendar screen
- [ ] refactor reducers and actions for Albums screen
- [ ] refactor reducers and actions for Event screen
- [ ] refactor reducers and actions for Poll screen for invitees
- [ ] refactor reducers and actions for ConfirmEvent screen for invitees
- [ ] refactor reducers and actions for Poll screen for host
- [ ] refactor reducers and actions for ConfirmEvent screen for host
- [ ] summary page for creating event
- [ ] summary page reducers and actions
- [ ] upload profile photo page 
- [ ] extra filed for event code 
- [ ] forgot password on login page
- [ ] form page for reseting password
- [ ] create invite more friends feature
- [ ] refactor reducers and actions delete the event
- [ ] sockets

**Comment by minaorangina** [comment]
This issue was moved to DRDD2016/native#6
